include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    prefer_const_constructors: true
    prefer_final_fields: true
