name: flutter_chrome_extension
description: Manifest V3 Chrome extension popup built with Flutter Web.
repository: https://github.com/gabrimatic/flutter_chrome_extension
issue_tracker: https://github.com/gabrimatic/flutter_chrome_extension/issues

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"


dependencies:
  cupertino_icons: ^1.0.9
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
